version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress:/var/www/html
      - ./wp-content/themes/php-components:/var/www/html/wp-content/themes/php-components:delegated
    depends_on:
      - mysql
    networks:
      - wordpress

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: admin
      MYSQL_PASSWORD: password 
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - wordpress

networks:
  wordpress:

volumes:
  wordpress:
  mysql:
